name: nlp8-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas==1.5.2
  - scikit-learn==1.0.2
  - matplotlib==3.5.2
  - seaborn==0.11.2
  - tqdm==4.64.1
  - pip:
      - pytubefix
      - whisper==1.0.0
      - torch==2.0.0
      - transformers==4.28.0
      - accelerate>=0.21.0
      - datasets==2.8.0
      - tensorflow==2.10.0
      - emoji==2.1.0
      - textblob==0.17.1
      - requests==2.28.1
      - contractions==0.1.72
      - azureml-core
